version: "2"
services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/user/appdata/airsonic/config:/config
      - /mnt/disks/MYCLOUDEX2ULTRA_Media/Music:/music
      - /mnt/user/appdata/airsonic/playlists:/playlists
      - /mnt/disks/MYCLOUDEX2ULTRA_Media/Podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped
