version: "2"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/user/appdata/lidarr/config:/config
      - /mnt/disks/MyCloudEX2/Music:/music
      - /mnt/cache/nzb_media/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/user/appdata/airsonic/config:/config
      - /mnt/disks/MyCloudEX2/Music:/music
      - /mnt/user/appdata/airsonic/playlists:/playlists
      - /mnt/disks/MyCloudEX2/Podcasts:/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped
