version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /shares/MyCloud/TV:/MyCloud
      - /shares/MyCloud_ext/TV:/MyCloud_ext
      - /shares/MyCloudEX2/TV:/MyCloudEX2
      - /shares/MyCloudEX2_2/TV:MyCloudEX2_2
      - /mnt/nzb_media/Downloads:/downloads
      - /home/proxdox/nzb/sonarr/config:/config
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /shares/MyCloud/Movies:/MyCloud
      - /shares/MyCloud_ext/Movies:/MyCloud_ext
      - /shares/MyCloudEX2/Movies:/MyCloudEX2
      - /shares/MyCloudEX2_2/Movies:MyCloudEX2_2
      - /mnt/nzb_media/Downloads:/downloads
      - /home/proxdox/nzb/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped
  radarr_4K:
    image: linuxserver/radarr
    container_name: radarr_4K
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /shares/MyCloudEX2_2/4K_Movies:MyCloudEX2_2
      - /mnt/nzb_media/Downloads:/downloads
      - /home/proxdox/nzb/radarr_4k/config:/config
    ports:
      - 7777:7878
    restart: unless-stopped
