version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  organizr-v2:
    image: organizrtools/organizr-v2
    container_name: organizr-v2
    ports:
      - 82:80
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - /home/plex/nzb/organizrV2/config:/config
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/plex/nzb/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/plex/tautulli/config:/config
     # - path to plex logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
    
  
